export default function AboutPage() {
  return (
    <div className="text-center p-10">
      <h1 className="text-2xl font-bold my-4">About</h1>
      <p className="text-gray-300">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti, obcaecati excepturi. Error laudantium quidem molestiae iusto nemo est pariatur, tempora molestias unde, voluptatem quia. Ipsum doloremque dolor qui ipsa sapiente odio, esse sequi veniam vel, quaerat voluptate nemo accusamus reprehenderit enim! Quibusdam, molestiae nulla ipsam magni, omnis, optio at alias neque ratione ad nam voluptatibus dicta earum fugiat doloremque reprehenderit ea perferendis consequatur eveniet? A dolorem natus, distinctio ullam omnis facere impedit odio modi beatae eveniet dolores laboriosam rerum harum, sapiente, debitis tempore. Dolorum ea dolorem eos nesciunt saepe laudantium molestiae veniam. Laborum qui ratione quis rerum expedita consectetur numquam reprehenderit eligendi molestias, error quia facere accusantium eius provident. Ex a velit earum iure ipsa deleniti dolor illo suscipit, eum et ducimus dolore nam accusamus doloribus rem quaerat commodi vero nesciunt aperiam neque exercitationem aspernatur. Quisquam voluptatem eos vitae quidem et laborum unde nostrum repudiandae rerum, animi asperiores placeat eius. Id eos nisi nihil excepturi tenetur aliquam explicabo quam a eaque ipsam recusandae nobis pariatur et adipisci ab quisquam, quae expedita repellat! Perspiciatis iste dolorum, nemo temporibus, quo eos at nam voluptate sequi dignissimos id cupiditate itaque rerum quod repellendus aspernatur quibusdam voluptatum corrupti officiis? Aliquid similique nam cumque quis aperiam qui hic eligendi rem sunt, ipsa eius porro, fugit laboriosam consequatur at obcaecati minus quia illo. Omnis nihil ex culpa rerum, nesciunt praesentium deleniti magnam quo obcaecati atque fuga, debitis eius. Voluptatibus cupiditate amet, pariatur similique excepturi aperiam inventore ea, impedit fugit at cum dicta atque repellendus assumenda. Facere sed quod omnis id illum culpa, inventore soluta error! Nihil eligendi possimus voluptate officiis quidem ipsam itaque sequi saepe nemo distinctio nisi fugiat tempora, error voluptatibus consectetur provident numquam vero accusamus aliquid esse quam fuga totam ab earum? Ducimus quos nemo quidem quod quis non libero cupiditate assumenda deserunt ea.
      </p>
    </div>
  )
}
