import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <nav className='bg-slate-200 text-gray-700 h-20 flex flex-row items-center justify-end gap-2 pr-2'>
            <a className='h-full bg-sky-600 flex items-center justify-center px-4 text-gray-200' href="/products">Products</a>
            <a className='h-full bg-sky-600 flex items-center justify-center px-4 text-gray-200' href="/new">New Product</a>
          </nav>
          {children}
        </div>
      </body>
    </html>
  )
}
